debug: true

spring:
  profiles:
#    active: local
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info